DATASET_PATH = "dataset"
DATASET_FORMAT = "*.mid"
SEQUENCE_LENGTH = 15
OUTPUT_LENGTH = 100
MAX_NOTES = 72000
BATCH_SIZE = 64
DESIRED_INSTRUMENT = "Electric Guitar"
MODEL_LOSS = "categorical_crossentropy"
MODEL_PATH = "output/blues-generator.h5"
INSTRUMENT_PATH = "output/instrument"
NOTE_PATH = "output/notes"
PLOT_PATH = "output/plot.png"
NEW_MUSIC = "output/new_music.mid"
LEARNING_RATE = 1e-3
EPOCHS = 200
