import os
import argparse
from helper import constant
from neural_network import NeuralNetwork

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("-m", "--model", default=constant.MODEL_PATH, help="path to neural network model")
    ap.add_argument("-n", "--notes", default=constant.NOTE_PATH, help="path to notes generated by training")
    ap.add_argument(
        "-p",
        "--partition_info",
        default=constant.PARTITION_INFO_PATH,
        help="information about the partition on which the training was performed"
    )
    args = vars(ap.parse_args())

    neural_network = NeuralNetwork()
    neural_network.run(args)

